version: '2'
services:
    hercules_api:
        build:
            context: ./api
            args:
                port: ${PORT}
        image: hercules_api:dev
        container_name: hercules_api
        ports:
            - ${PORT}:${PORT}
        env_file: .env
        depends_on:
            - hercules_db
        links:
            - hercules_db
        volumes:
            - ./api:/usr/src/api
    hercules_db:
        image: mongo:3.2
        container_name: hercules_db
        volumes:
            - data:/data/db
volumes:
    data:
        external: false
