version: '2'
services:
    hercules_api:
        build:
            context: ./api
            dockerfile: Dockerfile.prod
        image: hercules_api:prod
        container_name: hercules_api
        ports: 
            - 80:3000
        env_file: .env
        depends_on:
            - hercules_db
        links:
            - hercules_db
        restart: always
    hercules_db:
        image: mongo:3.2
        container_name: hercules_db
        volumes: 
            - data:/data/db
        restart: always
volumes:
    data:
        external: false

    
        
