version: '2'
services:
    hercules_api:
        build:
            context: ./api
        image: hercules_api:dev
        container_name: hercules_api
        ports: 
            - 3000:3000
        env_file: .env
        depends_on:
            - hercules_db
        links:
            - hercules_db
        volumes:
            - ${HERCULES_PATH}:/usr/src/app
    hercules_db:
        image: mongo:3.2
        container_name: hercules_db
        volumes: 
            - data:/data/db
volumes:
    data:
        external: false

    
        
