FROM node:6.9-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm install pm2 -g

COPY package.json /usr/src/app
RUN npm install

COPY . /usr/src/app

EXPOSE 3000

CMD ["pm2-docker", "index.js"] 
